### ISSUE TITLE
Blocking call(gocode_complete) aborted: Install is not done

### ISSUE THREAD

**Issue by pwaller** [DisposaBoy/GoSublime#599]
This morning I used gosublime as I do every morning and it doesn't work.

The log is full of:
```
** 2015-02-06 10:35:14.266137 **:
GsComplete: Blocking call(gocode_complete) aborted: Install is not done
--------------------------------
```

At the very top of the log:

```
GoSublime r14.12.06-1: init mod(sh)

Traceback (most recent call last):
  File "./GoSublime.py", line 63, in plugin_loaded
    'margo_exe': MARGO_EXE,
  File "/home/pwaller/.config/sublime-text-2/Packages/GoSublime/gosubl/sh.py", line 260, in gs_init
    dur,
  File "/home/pwaller/.config/sublime-text-2/Packages/GoSublime/gosubl/sh.py", line 266, in _print
    print('GoSublime %s sh: %s' % (about.VERSION, s))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb5' in position 320: ordinal not in range(128)
```

```
$ go version
go version go1.4 linux/amd64
$ python -V
Python 2.7.6
```

**Comment by pwaller** [comment]
I've observed this on two separate installs.

**Comment by pwaller** [comment]
As far as I'm aware, I've encountered this less recently.

Tidying up my personal issues list, so closing this. Please create a new issue if you're still interested in tracking it.
