### ISSUE TITLE
What to do with problems like this？

### ISSUE THREAD

**Issue by ablegao** [DisposaBoy/GoSublime#619]
GoSublime r14.12.06-1: init mod(gs)
GoSublime r14.12.06-1: init mod(sh)
Traceback (most recent call last):
  File "/Users/gao/Library/Application Support/Sublime Text 3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 158, in on_api_ready
    m.plugin_loaded()
  File "/Users/gao/Library/Application Support/Sublime Text 3/Packages/GoSublime/GoSublime.py", line 63, in plugin_loaded
    'margo_exe': MARGO_EXE,
  File "/Users/gao/Library/Application Support/Sublime Text 3/Packages/GoSublime/gosubl/sh.py", line 205, in gs_init
    cr = ShellCommand(cmd_str).run()
  File "/Users/gao/Library/Application Support/Sublime Text 3/Packages/GoSublime/gosubl/sh.py", line 103, in run
    pr = self.proc()
  File "/Users/gao/Library/Application Support/Sublime Text 3/Packages/GoSublime/gosubl/sh.py", line 61, in proc
    nv = env(nv0)
  File "/Users/gao/Library/Application Support/Sublime Text 3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

**Comment by plamennikolov** [comment]
I'm receiving the same issue. Any thoughts?
