### ISSUE TITLE
go1.7rc1: PANIC: One of the package cache updaters panicked

### ISSUE THREAD

**Issue by runningmaster** [DisposaBoy/GoSublime#720]
Note: also I have this problem on go1.6.2

```
$ git clone git@github.com:DisposaBoy/GoSublime.git
```

```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/dmitriy/Development/go1.7rc1.path"
GORACE=""
GOROOT="/home/dmitriy/Development/go1.7rc1"
GOTOOLDIR="/home/dmitriy/Development/go1.7rc1/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build050827716=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

```

```
$ cat log.txt
Gocode pkg: "main"
Gocode env: gocode.margoEnv{LibPath:"/home/dmitriy/Development/go1.7rc1/pkg/linux_amd64:/home/dmitriy/Development/m12/src/vendor/pkg/linux_amd64:/home/dmitriy/Development/m12/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"/home/dmitriy/Development/go1.7rc1", GOPATH:"/home/dmitriy/Development/m12/src/vendor:/home/dmitriy/Development/m12", InstallSuffix:""}
margo: 2016/07/08 14:57:26 broker.go:105: gocode_calltip#mg9.autoken.de54a7c9-4104-43f3-a6df-7acaae46359f PANIC: One of the package cache updaters panicked
goroutine 41 [running]:
disposa.blue/cmd/margo_pkg.(*Broker).call.func1(0xc4200f8260, 0xc4200aa850)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:104 +0xc2
panic(0x7ee560, 0xc420016780)
    /home/dmitriy/Development/go1.7rc1/src/runtime/panic.go:458 +0x243
disposa.blue/something-borrowed/gocode.update_packages(0xc420043810)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/autocompletecontext.go:382 +0x1f0
disposa.blue/something-borrowed/gocode.(*auto_complete_context).update_caches(0xc420018a00)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/autocompletecontext.go:166 +0x1d9
disposa.blue/something-borrowed/gocode.(*auto_complete_context).apropos(0xc420018a00, 0xc4201063c0, 0x1c6, 0x1e0, 0xc42010d080, 0x2e, 0xb1, 0x2, 0x2, 0xc42010d080, ...)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/autocompletecontext.go:303 +0x1d9
disposa.blue/something-borrowed/gocode.(*margoState).Complete(0xc42012e000, 0x1, 0x0, 0x0, 0xc42010d050, 0x22, 0xc4200f9cc0, 0x2, 0x2, 0xc4201063c0, ...)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/gosublime_gocode_bridge.go:78 +0x144
disposa.blue/cmd/margo_pkg.(*mGocode).completions(0xc420108080, 0xc4201063c0, 0x1c6, 0x1e0, 0xc42010d080, 0x2e, 0xb1, 0xc420032800, 0x451ec0, 0xc420032800)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/m_gocode.go:95 +0x144
disposa.blue/cmd/margo_pkg.(*mGocode).calltips(0xc420108080, 0xc4201063c0, 0x1c6, 0x1e0, 0xc42010d080, 0x2e, 0xad, 0x0, 0x0, 0x0)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/m_gocode.go:105 +0x196
disposa.blue/cmd/margo_pkg.(*mGocode).Call(0xc420108080, 0x8bfdf8, 0xc4200f8260, 0xc4200aa850, 0x3)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/m_gocode.go:74 +0x159
disposa.blue/cmd/margo_pkg.(*Broker).call(0xc4200aa850, 0xc4200f8260, 0xa5db40, 0xc420108080)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:113 +0x9a
disposa.blue/cmd/margo_pkg.(*Broker).worker(0xc4200aa850, 0xc420016920, 0xc42000e360)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:188 +0xda
created by disposa.blue/cmd/margo_pkg.(*Broker).Loop
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:209 +0x124

goroutine 1 [syscall]:
syscall.Syscall(0x0, 0x0, 0xc4200ae000, 0x1000, 0x19, 0x7f8bc6de821f, 0x7f8bc6e9c502)
    /home/dmitriy/Development/go1.7rc1/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x0, 0xc4200ae000, 0x1000, 0x1000, 0x41c787, 0x7f8bc6d980c0, 0x7ee560)
    /home/dmitriy/Development/go1.7rc1/src/syscall/zsyscall_linux_amd64.go:783 +0x55
syscall.Read(0x0, 0xc4200ae000, 0x1000, 0x1000, 0x0, 0x41013d, 0xc4200b0c00)
    /home/dmitriy/Development/go1.7rc1/src/syscall/syscall_unix.go:161 +0x49
os.(*File).read(0xc420030008, 0xc4200ae000, 0x1000, 0x1000, 0xc420112580, 0xc42002af90, 0xc42006b798)
    /home/dmitriy/Development/go1.7rc1/src/os/file_unix.go:228 +0x4f
os.(*File).Read(0xc420030008, 0xc4200ae000, 0x1000, 0x1000, 0xc4200b0c00, 0xc4201045a0, 0xc4200b35d0)
    /home/dmitriy/Development/go1.7rc1/src/os/file.go:101 +0x59
bufio.(*Reader).fill(0xc4201161e0)
    /home/dmitriy/Development/go1.7rc1/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).ReadSlice(0xc4201161e0, 0x403b0a, 0xc42000e360, 0xc4201045a0, 0xc42006ba40, 0xc42006b8c8, 0x819940)
    /home/dmitriy/Development/go1.7rc1/src/bufio/bufio.go:330 +0xb5
bufio.(*Reader).ReadBytes(0xc4201161e0, 0xc42000e30a, 0xc42006ba40, 0x0, 0x0, 0x0, 0x0)
    /home/dmitriy/Development/go1.7rc1/src/bufio/bufio.go:408 +0x66
disposa.blue/cmd/margo_pkg.(*Broker).accept(0xc4200aa850, 0xc42000e360, 0xc4200aa800)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:128 +0x59
disposa.blue/cmd/margo_pkg.(*Broker).Loop(0xc4200aa850, 0x8b0001)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:213 +0x156
disposa.blue/cmd/margo_pkg.Main()
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/main.go:140 +0x755
main.main()
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo/main.go:8 +0x14

goroutine 34 [runnable]:
disposa.blue/something-borrowed/gocode.new_file_reader.func1(0xc420110140)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/utils.go:176 +0xa1
created by disposa.blue/something-borrowed/gocode.new_file_reader
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/utils.go:180 +0x8a

goroutine 18 [chan receive]:
disposa.blue/cmd/margo_pkg.init.2.func1()
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/g_autoinst.go:114 +0x92
created by disposa.blue/cmd/margo_pkg.init.2
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/g_autoinst.go:117 +0x35

goroutine 19 [sleep, locked to thread]:
time.Sleep(0x77359400)
    /home/dmitriy/Development/go1.7rc1/src/runtime/time.go:59 +0xe1
disposa.blue/cmd/margo_pkg.startOomKiller.func1(0x3e8)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/oom.go:31 +0x166
created by disposa.blue/cmd/margo_pkg.startOomKiller
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/oom.go:33 +0x3f

goroutine 37 [sleep]:
time.Sleep(0x6fc23ac00)
    /home/dmitriy/Development/go1.7rc1/src/runtime/time.go:59 +0xe1
disposa.blue/cmd/margo_pkg.Main.func1(0x6fc23ac00, 0xc4200aa850, 0xc420016730)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/main.go:122 +0x40
created by disposa.blue/cmd/margo_pkg.Main
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/main.go:131 +0x877

goroutine 38 [chan receive]:
disposa.blue/cmd/margo_pkg.Main.func2(0xc4200aa850)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/main.go:135 +0x7b
created by disposa.blue/cmd/margo_pkg.Main
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/main.go:138 +0x725

goroutine 40 [runnable]:
go/parser.(*parser).expectSemi(0xc420118000)
    /home/dmitriy/Development/go1.7rc1/src/go/parser/parser.go:410
go/parser.(*parser).parseFile(0xc420118000, 0x0)
    /home/dmitriy/Development/go1.7rc1/src/go/parser/parser.go:2468 +0xd6
go/parser.ParseFile(0xc420018a40, 0x0, 0x0, 0x7e98a0, 0xc4200f83c0, 0x20, 0x0, 0x0, 0x0)
    /home/dmitriy/Development/go1.7rc1/src/go/parser/interface.go:121 +0x1dc
disposa.blue/something-borrowed/gocode.(*auto_complete_file).process_data(0xc4200d6850, 0xc4202bab40, 0x1c7, 0x1c7)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/autocompletefile.go:69 +0x127
disposa.blue/something-borrowed/gocode.(*auto_complete_context).apropos(0xc420018a00, 0xc4202ba1e0, 0x1c6, 0x1e0, 0xc420154150, 0x2e, 0xb1, 0x2, 0x2, 0xc420154150, ...)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/autocompletecontext.go:298 +0x1c8
disposa.blue/something-borrowed/gocode.(*margoState).Complete(0xc42012e000, 0x1, 0x0, 0x0, 0xc420154120, 0x22, 0xc42008c9e0, 0x2, 0x2, 0xc4202ba1e0, ...)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/gosublime_gocode_bridge.go:78 +0x144
disposa.blue/cmd/margo_pkg.(*mGocode).completions(0xc420112080, 0xc4202ba1e0, 0x1c6, 0x1e0, 0xc420154150, 0x2e, 0xb1, 0xc4200b0c00, 0x451ec0, 0xc4200b0c00)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/m_gocode.go:95 +0x144
disposa.blue/cmd/margo_pkg.(*mGocode).calltips(0xc420112080, 0xc4202ba1e0, 0x1c6, 0x1e0, 0xc420154150, 0x2e, 0xad, 0x0, 0x48, 0x48)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/m_gocode.go:105 +0x196
disposa.blue/cmd/margo_pkg.(*mGocode).Call(0xc420112080, 0x8bfdf8, 0xc42008c0c0, 0xc4200aa850, 0x3)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/m_gocode.go:74 +0x159
disposa.blue/cmd/margo_pkg.(*Broker).call(0xc4200aa850, 0xc42008c0c0, 0xa5db40, 0xc420112080)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:113 +0x9a
disposa.blue/cmd/margo_pkg.(*Broker).worker(0xc4200aa850, 0xc420016920, 0xc42000e360)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:188 +0xda
created by disposa.blue/cmd/margo_pkg.(*Broker).Loop
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:209 +0x124

goroutine 21 [semacquire]:
sync.runtime_Semacquire(0xc42012e004)
    /home/dmitriy/Development/go1.7rc1/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc42012e000)
    /home/dmitriy/Development/go1.7rc1/src/sync/mutex.go:85 +0xd0
disposa.blue/something-borrowed/gocode.(*margoState).Complete(0xc42012e000, 0x1, 0x0, 0x0, 0xc4201546f0, 0x22, 0xc42008d320, 0x2, 0x2, 0xc4202ba5a0, ...)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/gosublime_gocode_bridge.go:73 +0x69
disposa.blue/cmd/margo_pkg.(*mGocode).completions(0xc420112300, 0xc4202ba5a0, 0x1c6, 0x1e0, 0xc420154720, 0x2e, 0xb1, 0xc4200b0c00, 0x451ec0, 0xc4200b0c00)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/m_gocode.go:95 +0x144
disposa.blue/cmd/margo_pkg.(*mGocode).calltips(0xc420112300, 0xc4202ba5a0, 0x1c6, 0x1e0, 0xc420154720, 0x2e, 0xad, 0x0, 0x48, 0x48)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/m_gocode.go:105 +0x196
disposa.blue/cmd/margo_pkg.(*mGocode).Call(0xc420112300, 0x8bfdf8, 0xc42008ca00, 0xc4200aa850, 0x3)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/m_gocode.go:74 +0x159
disposa.blue/cmd/margo_pkg.(*Broker).call(0xc4200aa850, 0xc42008ca00, 0xa5db40, 0xc420112300)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:113 +0x9a
disposa.blue/cmd/margo_pkg.(*Broker).worker(0xc4200aa850, 0xc420016920, 0xc42000e360)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:188 +0xda
created by disposa.blue/cmd/margo_pkg.(*Broker).Loop
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:209 +0x124

goroutine 22 [chan receive]:
disposa.blue/cmd/margo_pkg.(*Broker).worker(0xc4200aa850, 0xc420016920, 0xc42000e360)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:187 +0x8a
created by disposa.blue/cmd/margo_pkg.(*Broker).Loop
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:209 +0x124

goroutine 23 [semacquire]:
sync.runtime_Semacquire(0xc42012e004)
    /home/dmitriy/Development/go1.7rc1/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc42012e000)
    /home/dmitriy/Development/go1.7rc1/src/sync/mutex.go:85 +0xd0
disposa.blue/something-borrowed/gocode.(*margoState).Complete(0xc42012e000, 0x1, 0x0, 0x0, 0xc420154cc0, 0x22, 0xc42008dc60, 0x2, 0x2, 0xc4202ba960, ...)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/gosublime_gocode_bridge.go:73 +0x69
disposa.blue/cmd/margo_pkg.(*mGocode).completions(0xc420112580, 0xc4202ba960, 0x1c6, 0x1e0, 0xc420154cf0, 0x2e, 0xb1, 0xc4200b0c00, 0x451ec0, 0xc4200b0c00)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/m_gocode.go:95 +0x144
disposa.blue/cmd/margo_pkg.(*mGocode).calltips(0xc420112580, 0xc4202ba960, 0x1c6, 0x1e0, 0xc420154cf0, 0x2e, 0xad, 0x0, 0x48, 0x48)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/m_gocode.go:105 +0x196
disposa.blue/cmd/margo_pkg.(*mGocode).Call(0xc420112580, 0x8bfdf8, 0xc42008d340, 0xc4200aa850, 0x3)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/m_gocode.go:74 +0x159
disposa.blue/cmd/margo_pkg.(*Broker).call(0xc4200aa850, 0xc42008d340, 0xa5db40, 0xc420112580)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:113 +0x9a
disposa.blue/cmd/margo_pkg.(*Broker).worker(0xc4200aa850, 0xc420016920, 0xc42000e360)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:188 +0xda
created by disposa.blue/cmd/margo_pkg.(*Broker).Loop
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:209 +0x124

goroutine 24 [chan receive]:
disposa.blue/cmd/margo_pkg.(*Broker).worker(0xc4200aa850, 0xc420016920, 0xc42000e360)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:187 +0x8a
created by disposa.blue/cmd/margo_pkg.(*Broker).Loop
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:209 +0x124

goroutine 25 [chan receive]:
disposa.blue/cmd/margo_pkg.(*Broker).worker(0xc4200aa850, 0xc420016920, 0xc42000e360)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:187 +0x8a
created by disposa.blue/cmd/margo_pkg.(*Broker).Loop
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:209 +0x124

goroutine 26 [chan receive]:
disposa.blue/cmd/margo_pkg.(*Broker).worker(0xc4200aa850, 0xc420016920, 0xc42000e360)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:187 +0x8a
created by disposa.blue/cmd/margo_pkg.(*Broker).Loop
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:209 +0x124

goroutine 27 [chan receive]:
disposa.blue/cmd/margo_pkg.(*Broker).worker(0xc4200aa850, 0xc420016920, 0xc42000e360)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:187 +0x8a
created by disposa.blue/cmd/margo_pkg.(*Broker).Loop
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:209 +0x124

goroutine 28 [chan receive]:
disposa.blue/cmd/margo_pkg.(*Broker).worker(0xc4200aa850, 0xc420016920, 0xc42000e360)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:187 +0x8a
created by disposa.blue/cmd/margo_pkg.(*Broker).Loop
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:209 +0x124

goroutine 29 [chan receive]:
disposa.blue/cmd/margo_pkg.(*Broker).worker(0xc4200aa850, 0xc420016920, 0xc42000e360)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:187 +0x8a
created by disposa.blue/cmd/margo_pkg.(*Broker).Loop
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:209 +0x124

goroutine 42 [chan receive]:
disposa.blue/cmd/margo_pkg.(*Broker).worker(0xc4200aa850, 0xc420016920, 0xc42000e360)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:187 +0x8a
created by disposa.blue/cmd/margo_pkg.(*Broker).Loop
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:209 +0x124

goroutine 43 [chan receive]:
disposa.blue/cmd/margo_pkg.(*Broker).worker(0xc4200aa850, 0xc420016920, 0xc42000e360)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:187 +0x8a
created by disposa.blue/cmd/margo_pkg.(*Broker).Loop
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:209 +0x124

goroutine 44 [chan receive]:
disposa.blue/cmd/margo_pkg.(*Broker).worker(0xc4200aa850, 0xc420016920, 0xc42000e360)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:187 +0x8a
created by disposa.blue/cmd/margo_pkg.(*Broker).Loop
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:209 +0x124

goroutine 10 [chan receive]:
disposa.blue/cmd/margo_pkg.(*Broker).worker(0xc4200aa850, 0xc420016920, 0xc42000e360)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:187 +0x8a
created by disposa.blue/cmd/margo_pkg.(*Broker).Loop
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:209 +0x124

goroutine 11 [chan receive]:
disposa.blue/cmd/margo_pkg.(*Broker).worker(0xc4200aa850, 0xc420016920, 0xc42000e360)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:187 +0x8a
created by disposa.blue/cmd/margo_pkg.(*Broker).Loop
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:209 +0x124

goroutine 12 [chan receive]:
disposa.blue/cmd/margo_pkg.(*Broker).worker(0xc4200aa850, 0xc420016920, 0xc42000e360)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:187 +0x8a
created by disposa.blue/cmd/margo_pkg.(*Broker).Loop
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:209 +0x124

goroutine 13 [chan receive]:
disposa.blue/cmd/margo_pkg.(*Broker).worker(0xc4200aa850, 0xc420016920, 0xc42000e360)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:187 +0x8a
created by disposa.blue/cmd/margo_pkg.(*Broker).Loop
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:209 +0x124

goroutine 14 [chan receive]:
disposa.blue/cmd/margo_pkg.(*Broker).worker(0xc4200aa850, 0xc420016920, 0xc42000e360)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:187 +0x8a
created by disposa.blue/cmd/margo_pkg.(*Broker).Loop
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:209 +0x124

goroutine 15 [chan receive]:
disposa.blue/cmd/margo_pkg.(*Broker).worker(0xc4200aa850, 0xc420016920, 0xc42000e360)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:187 +0x8a
created by disposa.blue/cmd/margo_pkg.(*Broker).Loop
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:209 +0x124

goroutine 16 [chan send]:
disposa.blue/something-borrowed/gocode.(*package_file_cache).update_cache(0xc4202ab640)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/package.go:86 +0x14a
disposa.blue/something-borrowed/gocode.update_packages.func1(0xc420116780, 0xc4202ab640)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/autocompletecontext.go:374 +0x55
created by disposa.blue/something-borrowed/gocode.update_packages
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/autocompletecontext.go:376 +0xdc

goroutine 65 [chan send]:
disposa.blue/something-borrowed/gocode.update_packages.func1.1(0xc420116780)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/autocompletecontext.go:371 +0x7b
panic(0x807360, 0xc420294200)
    /home/dmitriy/Development/go1.7rc1/src/runtime/panic.go:458 +0x243
disposa.blue/something-borrowed/gocode.(*gc_bin_parser).parse_export(0xc4202bc000, 0xc4200c2ca0)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/package_bin.go:101 +0x562
disposa.blue/something-borrowed/gocode.(*package_file_cache).process_package_data(0xc4202ab680, 0xc4242e2000, 0x837f, 0x857f)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/package.go:141 +0x460
disposa.blue/something-borrowed/gocode.(*package_file_cache).update_cache(0xc4202ab680)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/package.go:90 +0x216
disposa.blue/something-borrowed/gocode.update_packages.func1(0xc420116780, 0xc4202ab680)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/autocompletecontext.go:374 +0x55
created by disposa.blue/something-borrowed/gocode.update_packages
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/autocompletecontext.go:376 +0xdc

goroutine 66 [runnable]:
disposa.blue/something-borrowed/gocode.(*package_file_cache).process_package_data(0xc4202ab6c0, 0xc4242f4000, 0x254a1, 0x256a1)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/package.go:105 +0x1d5
disposa.blue/something-borrowed/gocode.(*package_file_cache).update_cache(0xc4202ab6c0)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/package.go:90 +0x216
disposa.blue/something-borrowed/gocode.update_packages.func1(0xc420116780, 0xc4202ab6c0)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/autocompletecontext.go:374 +0x55
created by disposa.blue/something-borrowed/gocode.update_packages
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/autocompletecontext.go:376 +0xdc

goroutine 67 [chan send]:
disposa.blue/something-borrowed/gocode.update_packages.func1.1(0xc420116780)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/autocompletecontext.go:371 +0x7b
panic(0x807360, 0xc420294080)
    /home/dmitriy/Development/go1.7rc1/src/runtime/panic.go:458 +0x243
disposa.blue/something-borrowed/gocode.(*gc_bin_parser).parse_export(0xc4202d0000, 0xc420294050)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/package_bin.go:101 +0x562
disposa.blue/something-borrowed/gocode.(*package_file_cache).process_package_data(0xc4202ab700, 0xc4202d2000, 0x4dd9, 0x4fd9)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/package.go:141 +0x460
disposa.blue/something-borrowed/gocode.(*package_file_cache).update_cache(0xc4202ab700)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/package.go:90 +0x216
disposa.blue/something-borrowed/gocode.update_packages.func1(0xc420116780, 0xc4202ab700)
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/autocompletecontext.go:374 +0x55
created by disposa.blue/something-borrowed/gocode.update_packages
    /home/dmitriy/.config/sublime-text-3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/autocompletecontext.go:376 +0xdc

```

**Comment by DisposaBoy** [comment]
Make sure you packages are up-to-date, my only guess is that your package cache contains stale packages built on `go1.6` and `go1.7`.

Also your `go env` output doesn't mean anything unless it comes from within Sublime Text via `9o`.

**Comment by runningmaster** [comment]
@DisposaBoy 
Thank you for your guess. I removed folders Cache/GoSublime and Packages/User/GoSublime. After that I restarted text editor. Now all works fine.
