### ISSUE TITLE
MarGo build failed ~bin/gosublime.margo_r16.07.09-1_go1.6.2.exe (missing)

### ISSUE THREAD

**Issue by aeikenberry** [DisposaBoy/GoSublime#733]
```
| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['/usr/local/Cellar/go/1.6.2/libexec/bin/go', 'build', '-tags', '', '-v', '-o', 'gosublime.margo_r16.07.09-1_go1.6.2.exe', 'disposa.blue/cmd/margo']`
|                > stdout: `
|                > 
|                > `
|                > stderr: `
|                > disposa.blue/margo
|                > net
|                > disposa.blue/something-borrowed/types
|                > disposa.blue/margo/meth/importpaths
|                > crypto/x509
|                > net/textproto
|                > go build crypto/x509: /usr/local/Cellar/go/1.6.2/libexec/pkg/tool/darwin_amd64/compile: signal: segmentation fault
|                > fatal error: unexpected signal during runtime execution
|                > [signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x17cc60]
|                > 
|                > goroutine 7 [running]:
|                > runtime.throw(0x6898a0, 0x2a)
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:547 +0x90 fp=0xc82049f2b8 sp=0xc82049f2a0
|                > runtime.sigpanic()
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc82049f308 sp=0xc82049f2b8
|                > sync.(*Pool).Get(0x882700, 0x0, 0x0)
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/sync/pool.go:102 +0x40 fp=0xc82049f358 sp=0xc82049f308
|                > fmt.newPrinter(0x464bc0)
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:133 +0x27 fp=0xc82049f398 sp=0xc82049f358
|                > fmt.Sprintf(0x5f40c0, 0xf, 0xc82049f4c0, 0x2, 0x2, 0x0, 0x0)
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:202 +0x2b fp=0xc82049f3e8 sp=0xc82049f398
|                > fmt.Errorf(0x5f40c0, 0xf, 0xc82049f4c0, 0x2, 0x2, 0x0, 0x0)
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:212 +0x65 fp=0xc82049f450 sp=0xc82049f3e8
|                > main.(*builder).build.func1(0xc82049fe00, 0xc82024be10)
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/cmd/go/build.go:1352 +0x1ad fp=0xc82049f4e8 sp=0xc82049f450
|                > main.(*builder).build(0xc8201a0770, 0xc82024be10, 0xc00000, 0xc82048ebb0)
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/cmd/go/build.go:1492 +0x23c1 fp=0xc82049fdf0 sp=0xc82049f4e8
|                > main.(*builder).do.func1(0xc82024be10)
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/cmd/go/build.go:1257 +0x3b2 fp=0xc82049feb0 sp=0xc82049fdf0
|                > main.(*builder).do.func2(0xc820013320, 0xc8201a0770, 0xc82023ace0)
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/cmd/go/build.go:1314 +0x156 fp=0xc82049ff88 sp=0xc82049feb0
|                > runtime.goexit()
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82049ff90 sp=0xc82049ff88
|                > created by main.(*builder).do
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/cmd/go/build.go:1320 +0x39e
|                > 
|                > goroutine 1 [semacquire]:
|                > sync.runtime_Semacquire(0xc82001332c)
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/runtime/sema.go:47 +0x26
|                > sync.(*WaitGroup).Wait(0xc820013320)
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/sync/waitgroup.go:127 +0xb4
|                > main.(*builder).do(0xc8201a0770, 0xc8201eab60)
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/cmd/go/build.go:1323 +0x3c6
|                > main.runBuild(0x888ae0, 0xc82009e070, 0x1, 0x1)
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/cmd/go/build.go:479 +0x4dc
|                > main.main()
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/cmd/go/main.go:181 +0x783
|                > 
|                > goroutine 17 [syscall, locked to thread]:
|                > runtime.goexit()
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:1998 +0x1
|                > 
|                > goroutine 20 [syscall]:
|                > os/signal.signal_recv(0x0)
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/runtime/sigqueue.go:116 +0x132
|                > os/signal.loop()
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/os/signal/signal_unix.go:22 +0x18
|                > created by os/signal.init.1
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/os/signal/signal_unix.go:28 +0x37
|                > 
|                > goroutine 4 [select]:
|                > main.(*builder).do.func2(0xc820013320, 0xc8201a0770, 0xc82023ace0)
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/cmd/go/build.go:1304 +0x1cf
|                > created by main.(*builder).do
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/cmd/go/build.go:1320 +0x39e
|                > 
|                > goroutine 5 [select]:
|                > main.(*builder).do.func2(0xc820013320, 0xc8201a0770, 0xc82023ace0)
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/cmd/go/build.go:1304 +0x1cf
|                > created by main.(*builder).do
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/cmd/go/build.go:1320 +0x39e
|                > 
|                > goroutine 6 [select]:
|                > main.(*builder).do.func2(0xc820013320, 0xc8201a0770, 0xc82023ace0)
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/cmd/go/build.go:1304 +0x1cf
|                > created by main.(*builder).do
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/cmd/go/build.go:1320 +0x39e
|                > 
|                > goroutine 8 [select]:
|                > main.(*builder).do.func2(0xc820013320, 0xc8201a0770, 0xc82023ace0)
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/cmd/go/build.go:1304 +0x1cf
|                > created by main.(*builder).do
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/cmd/go/build.go:1320 +0x39e
|                > 
|                > goroutine 9 [select]:
|                > main.(*builder).do.func2(0xc820013320, 0xc8201a0770, 0xc82023ace0)
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/cmd/go/build.go:1304 +0x1cf
|                > created by main.(*builder).do
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/cmd/go/build.go:1320 +0x39e
|                > 
|                > goroutine 10 [select]:
|                > main.(*builder).do.func2(0xc820013320, 0xc8201a0770, 0xc82023ace0)
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/cmd/go/build.go:1304 +0x1cf
|                > created by main.(*builder).do
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/cmd/go/build.go:1320 +0x39e
|                > 
|                > goroutine 11 [select]:
|                > main.(*builder).do.func2(0xc820013320, 0xc8201a0770, 0xc82023ace0)
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/cmd/go/build.go:1304 +0x1cf
|                > created by main.(*builder).do
|                >  /usr/local/Cellar/go/1.6.2/libexec/src/cmd/go/build.go:1320 +0x39e
|                > `
|                > exception: `None`
|   install state: busy
| sublime.version: 3126
| sublime.channel: stable
|       about.ann: a16.07.09-1
|   about.version: r16.07.09-1
|         version: r16.07.09-1
|        platform: osx-x64
|            ~bin: ~/Library/Application Support/Sublime Text 3/Packages/User/GoSublime/osx-x64/bin
|       margo.exe: ~bin/gosublime.margo_r16.07.09-1_go1.6.2.exe (missing)
|          go.exe: /usr/local/Cellar/go/1.6.2/libexec/bin/go (ok)
|      go.version: go1.6.2
|          GOROOT: /usr/local/Cellar/go/1.6.2/libexec
|          GOPATH: ~/code/gosrc
|           GOBIN: (not set) (should usually be `(not set)`)
|       set.shell: []
|       env.shell: /usr/local/bin/zsh
|       shell.cmd: ['/usr/local/bin/zsh', '-l', '-c', '${CMD}']
```

**Comment by zyc21jxy** [comment]
hi,bro
do you know how to fix this issue now?

**Comment by Michael-Stanford** [comment]
I had this problem, but after installing Go version 1.7 everything seems to be working fine. Thanks to @sb10 on #736.
