### ISSUE TITLE
macOS Sierra 10.12 MarGo build failed -- same as #733

### ISSUE THREAD

**Issue by Michael-Stanford** [DisposaBoy/GoSublime#739]
Probably user error - but I have tried installing using 

    git clone https://github.com/DisposaBoy/GoSublime
and using Sublime Package Control, and get the same results. I also tried deleting all the GoSublime-named files and directory in the sublime packages/user directory.

Here's what it says in the Sublime console:
```
| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['/usr/local/go/bin/go', 'build', '-tags', '', '-v', '-o', 'gosublime.margo_r16.07.09-1_go1.6.3.exe', 'disposa.blue/cmd/margo'
'/usr/local/go/bin/go', 'build', '-tags', '', '-v', '-o', 'gosublime.margo_r16.07.09-1_go1.6.3.exe', 'disposa.blue/cmd/margo']`
|                > stdout: `
|                > 
|                > `
|                > stderr: `
|                > disposa.blue/margo
|                > net
|                > disposa.blue/something-borrowed/types
|                > disposa.blue/margo/meth/importpaths
|                > # disposa.blue/something-borrowed/types
|                > fatal error: unexpected signal during runtime execution
|                > [signal 0xb code=0x1 addr=0x145f026ae97e pc=0xf0eb]
|                > 
|                > runtime stack:
|                > runtime.throw(0x4971c0, 0x2a)
|                > 	/usr/local/go/src/runtime/panic.go:547 +0x90
|                > runtime.sigpanic()
|                > 	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
|                > runtime.unlock(0x982540)
|                > 	/usr/local/go/src/runtime/lock_sema.go:107 +0x14b
|                > runtime.(*mheap).alloc_m(0x982540, 0x1, 0x11, 0xf43e78)
|                > 	/usr/local/go/src/runtime/mheap.go:492 +0x314
|                > runtime.(*mheap).alloc.func1()
|                > 	/usr/local/go/src/runtime/mheap.go:502 +0x41
|                > runtime.systemstack(0xc820487e58)
|                > 	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab
|                > runtime.(*mheap).alloc(0x982540, 0x1, 0x10000000011, 0xed8f)
|                > 	/usr/local/go/src/runtime/mheap.go:503 +0x63
|                > runtime.(*mcentral).grow(0x983f80, 0x0)
|                > 	/usr/local/go/src/runtime/mcentral.go:209 +0x93
|                > runtime.(*mcentral).cacheSpan(0x983f80, 0xf43e78)
|                > 	/usr/local/go/src/runtime/mcentral.go:89 +0x47d
|                > runtime.(*mcache).refill(0xaf4960, 0xc800000011, 0xf43e78)
|                > 	/usr/local/go/src/runtime/mcache.go:119 +0xcc
|                > runtime.mallocgc.func2()
|                > 	/usr/local/go/src/runtime/malloc.go:642 +0x2b
|                > runtime.systemstack(0xc8204764c0)
|                > 	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
|                > runtime.mstart()
|                > 	/usr/local/go/src/runtime/proc.go:1051
|                > 
|                > goroutine 1 [running]:
|                > runtime.systemstack_switch()
|                > 	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc822905360 sp=0xc822905358
|                > runtime.mallocgc(0x100, 0x417e40, 0x0, 0xc8250fa300)
|                > 	/usr/local/go/src/runtime/malloc.go:643 +0x869 fp=0xc822905438 sp=0xc822905360
|                > runtime.newarray(0x417e40, 0x8, 0x0)
|                > 	/usr/local/go/src/runtime/malloc.go:798 +0xc9 fp=0xc822905478 sp=0xc822905438
|                > runtime.growslice(0x3b0780, 0xc8250fa280, 0x4, 0x4, 0x5, 0x0, 0x0, 0x0)
|                > 	/usr/local/go/src/runtime/slice.go:100 +0x2c1 fp=0xc8229054e8 sp=0xc822905478
|                > cmd/internal/obj.savedata(0xc8200ae000, 0xc8216d7680, 0xc824ce6b40, 0x4423c8, 0x7)
|                > 	/usr/local/go/src/cmd/internal/obj/data.go:92 +0x742 fp=0xc822905650 sp=0xc8229054e8
|                > cmd/internal/obj.Flushplist(0xc8200ae000)
|                > 	/usr/local/go/src/cmd/internal/obj/objfile.go:206 +0xf26 fp=0xc822905870 sp=0xc822905650
|                > cmd/internal/obj.Writeobjdirect(0xc8200ae000, 0xc821966200)
|                > 	/usr/local/go/src/cmd/internal/obj/objfile.go:114 +0x21 fp=0xc822905888 sp=0xc822905870
|                > cmd/compile/internal/gc.dumpobj()
|                > 	/usr/local/go/src/cmd/compile/internal/gc/obj.go:88 +0xe5f fp=0xc822905ac0 sp=0xc822905888
|                > cmd/compile/internal/gc.Main()
|                > 	/usr/local/go/src/cmd/compile/internal/gc/lex.go:495 +0x2225 fp=0xc822905de0 sp=0xc822905ac0
|                > cmd/compile/internal/amd64.Main()
|                > 	/usr/local/go/src/cmd/compile/internal/amd64/galign.go:127 +0x58d fp=0xc822905e48 sp=0xc822905de0
|                > main.main()
|                > 	/usr/local/go/src/cmd/compile/main.go:32 +0x395 fp=0xc822905f20 sp=0xc822905e48
|                > runtime.main()
|                > 	/usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc822905f70 sp=0xc822905f20
|                > runtime.goexit()
|                > 	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc822905f78 sp=0xc822905f70
|                > crypto/x509
|                > net/textproto
|                > mime/multipart
|                > crypto/tls
|                > net/http
|                > # net/http
|                > fatal error: unexpected signal during runtime execution
|                > [signal 0xb code=0x1 addr=0x145f7db1d0a8 pc=0xf0eb]
|                > 
|                > runtime stack:
|                > runtime.throw(0x4971c0, 0x2a)
|                > 	/usr/local/go/src/runtime/panic.go:547 +0x90
|                > runtime.sigpanic()
|                > 	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
|                > runtime.unlock(0x982540)
|                > 	/usr/local/go/src/runtime/lock_sema.go:107 +0x14b
|                > runtime.(*mheap).alloc_m(0x982540, 0x1, 0x4, 0xf07060)
|                > 	/usr/local/go/src/runtime/mheap.go:492 +0x314
|                > runtime.(*mheap).alloc.func1()
|                > 	/usr/local/go/src/runtime/mheap.go:502 +0x41
|                > runtime.systemstack(0xc820043e58)
|                > 	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab
|                > runtime.(*mheap).alloc(0x982540, 0x1, 0x10000000004, 0xed8f)
|                > 	/usr/local/go/src/runtime/mheap.go:503 +0x63
|                > runtime.(*mcentral).grow(0x9839d0, 0x0)
|                > 	/usr/local/go/src/runtime/mcentral.go:209 +0x93
|                > runtime.(*mcentral).cacheSpan(0x9839d0, 0xc82034ad50)
|                > 	/usr/local/go/src/runtime/mcentral.go:89 +0x47d
|                > runtime.(*mcache).refill(0xaf4000, 0x4, 0xc82034ad20)
|                > 	/usr/local/go/src/runtime/mcache.go:119 +0xcc
|                > runtime.mallocgc.func2()
|                > 	/usr/local/go/src/runtime/malloc.go:642 +0x2b
|                > runtime.systemstack(0xc82001c000)
|                > 	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
|                > runtime.mstart()
|                > 	/usr/local/go/src/runtime/proc.go:1051
|                > 
|                > goroutine 1 [running]:
|                > runtime.systemstack_switch()
|                > 	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc823589650 sp=0xc823589648
|                > runtime.mallocgc(0x30, 0x40a380, 0x0, 0x1dae06)
|                > 	/usr/local/go/src/runtime/malloc.go:643 +0x869 fp=0xc823589728 sp=0xc823589650
|                > runtime.newobject(0x40a380, 0x10)
|                > 	/usr/local/go/src/runtime/malloc.go:781 +0x42 fp=0xc823589750 sp=0xc823589728
|                > cmd/compile/internal/gc.Nodconst(0xc8237d6b40, 0xc8200b00f0, 0x8)
|                > 	/usr/local/go/src/cmd/compile/internal/gc/subr.go:654 +0x63 fp=0xc8235897d8 sp=0xc823589750
|                > cmd/compile/internal/gc.compile(0xc820c5b5f0)
|                > 	/usr/local/go/src/cmd/compile/internal/gc/pgen.go:477 +0xed1 fp=0xc823589a48 sp=0xc8235897d8
|                > cmd/compile/internal/gc.funccompile(0xc820c5b5f0)
|                > 	/usr/local/go/src/cmd/compile/internal/gc/dcl.go:1450 +0x1c0 fp=0xc823589ac0 sp=0xc823589a48
|                > cmd/compile/internal/gc.Main()
|                > 	/usr/local/go/src/cmd/compile/internal/gc/lex.go:472 +0x2116 fp=0xc823589de0 sp=0xc823589ac0
|                > cmd/compile/internal/amd64.Main()
|                > 	/usr/local/go/src/cmd/compile/internal/amd64/galign.go:127 +0x58d fp=0xc823589e48 sp=0xc823589de0
|                > main.main()
|                > 	/usr/local/go/src/cmd/compile/main.go:32 +0x395 fp=0xc823589f20 sp=0xc823589e48
|                > runtime.main()
|                > 	/usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc823589f70 sp=0xc823589f20
|                > runtime.goexit()
|                > 	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc823589f78 sp=0xc823589f70
|                > `
|                > exception: `None`
|   install state: busy
| sublime.version: 3126
| sublime.channel: stable
|       about.ann: a16.07.09-1
|   about.version: r16.07.09-1
|         version: r16.07.09-1
|        platform: osx-x64
|            ~bin: ~/Library/Application Support/Sublime Text 3/Packages/User/GoSublime/osx-x64/bin
|       margo.exe: ~bin/gosublime.margo_r16.07.09-1_go1.6.3.exe (missing)
|          go.exe: /usr/local/go/bin/go (ok)
|      go.version: go1.6.3
|          GOROOT: /usr/local/go
|          GOPATH: /users/michael/go
|           GOBIN: (not set) (should usually be `(not set)`)
|       set.shell: []
|       env.shell: /bin/bash
|       shell.cmd: ['/bin/bash', '-l', '-c', '${CMD}']
```

**Comment by Michael-Stanford** [comment]
Same as #733
