### ISSUE TITLE
MarGo build failed

### ISSUE THREAD

**Issue by rochael** [DisposaBoy/GoSublime#792]
```
> cmd: `['/usr/local/Cellar/go/1.5.2/libexec/bin/go', 'build', '-tags', '', '-v', '-o', 'gosublime.margo_r17.11.27-1_go?.exe', 'disposa.blue/cmd/margo']`
|                > stdout: `
|                > 
|                > `
|                > stderr: `
|                > disposa.blue/margo
|                > disposa.blue/something-borrowed/types
|                > net
|                > disposa.blue/margo/meth/importpaths
|                > net/textproto
|                > crypto/x509
|                > mime/multipart
|                > crypto/tls
|                > net/http
|                > net/rpc
|                > net/http/pprof
|                > disposa.blue/something-borrowed/gocode
|                > disposa.blue/cmd/margo_pkg
|                > disposa.blue/cmd/margo
|                > # disposa.blue/cmd/margo
|                > fatal error: unexpected signal during runtime execution
|                > [signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x1f2c9]
|                > 
|                > runtime stack:
|                > runtime.throw(0x2ad620, 0x2a)
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/panic.go:527 +0x90
|                > runtime.sigpanic()
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/sigpanic_unix.go:12 +0x5a
|                > runtime.(*gcWork).put(0xc82001f220, 0xc826f06000)
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/mgcwork.go:87 +0x49
|                > runtime.greyobject(0xc826f06000, 0x0, 0x0, 0xc81fc87cff, 0x0, 0x720fc0, 0xc82001f220)
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/mgcmark.go:1015 +0x2f1
|                > runtime.shade(0xc826f06000)
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/mgcmark.go:953 +0x9a
|                > runtime.gcmarkwb_m(0xc82007e060, 0xc826f06000)
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/mbarrier.go:91 +0xc1
|                > runtime.writebarrierptr_nostore1.func1()
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/mbarrier.go:117 +0x134
|                > runtime.systemstack(0xc82001e000)
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/asm_amd64.s:262 +0x79
|                > runtime.mstart()
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/proc1.go:668
|                > 
|                > goroutine 1 [running]:
|                > runtime.systemstack_switch()
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/asm_amd64.s:216 fp=0xc82003cad0 sp=0xc82003cac8
|                > runtime.writebarrierptr_nostore1(0xc82007e060, 0xc826f06000)
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/mbarrier.go:118 +0x71 fp=0xc82003cb08 sp=0xc82003cad0
|                > runtime.writebarrierptr(0xc82007e060, 0xc826f06000)
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/mbarrier.go:137 +0x4b fp=0xc82003cb38 sp=0xc82003cb08
|                > cmd/link/internal/ld._lookup(0xc82007e000, 0xc826f01000, 0x1a, 0x0, 0x1, 0xf)
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/cmd/link/internal/ld/sym.go:196 +0x270 fp=0xc82003cbb0 sp=0xc82003cb38
|                > cmd/link/internal/ld.Linklookup(0xc82007e000, 0xc826f01000, 0x1a, 0x0, 0xc826f01000)
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/cmd/link/internal/ld/sym.go:203 +0x48 fp=0xc82003cbe8 sp=0xc82003cbb0
|                > cmd/link/internal/ld.rdsym(0xc82007e000, 0xc826e27f00, 0xc8250770c0, 0xd, 0xc820d1b180)
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/cmd/link/internal/ld/objfile.go:459 +0x232 fp=0xc82003ccf8 sp=0xc82003cbe8
|                > cmd/link/internal/ld.readsym(0xc82007e000, 0xc826e27f00, 0xc8250770c0, 0xd, 0xc826dff9f0, 0x4b)
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/cmd/link/internal/ld/objfile.go:273 +0x1265 fp=0xc82003d140 sp=0xc82003ccf8
|                > cmd/link/internal/ld.ldobjfile(0xc82007e000, 0xc826e27f00, 0xc8250770c0, 0xd, 0xd4bf2, 0xc826dff9f0, 0x4b)
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/cmd/link/internal/ld/objfile.go:147 +0xa56 fp=0xc82003d350 sp=0xc82003d140
|                > cmd/link/internal/ld.ldobj(0xc826e27f00, 0xc8250770c0, 0xd, 0xd4c1b, 0xc826dff9f0, 0x4b, 0xc8228baf50, 0x43, 0x1)
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/cmd/link/internal/ld/lib.go:1208 +0x14e1 fp=0xc82003d5b8 sp=0xc82003d350
|                > cmd/link/internal/ld.objfile(0xc8236304d0)
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/cmd/link/internal/ld/lib.go:730 +0x10d5 fp=0xc82003d8c8 sp=0xc82003d5b8
|                > cmd/link/internal/ld.loadlib()
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/cmd/link/internal/ld/lib.go:482 +0x5ce fp=0xc82003d9f0 sp=0xc82003d8c8
|                > cmd/link/internal/ld.Ldmain()
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/cmd/link/internal/ld/pobj.go:212 +0x1c4c fp=0xc82003de70 sp=0xc82003d9f0
|                > cmd/link/internal/amd64.Main()
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/cmd/link/internal/amd64/obj.go:44 +0x19 fp=0xc82003de78 sp=0xc82003de70
|                > main.main()
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/cmd/link/main.go:26 +0x189 fp=0xc82003df50 sp=0xc82003de78
|                > runtime.main()
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/proc.go:111 +0x2b0 fp=0xc82003dfa0 sp=0xc82003df50
|                > runtime.goexit()
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc82003dfa8 sp=0xc82003dfa0
|                > `
|                > exception: `None`
|   install state: busy
| sublime.version: 3126
| sublime.channel: stable
|       about.ann: a17.11.27-1
|   about.version: r17.11.27-1
|         version: r17.11.27-1
|        platform: osx-x64
|            ~bin: ~/Library/Application Support/Sublime Text 3/Packages/User/GoSublime/osx-x64/bin
|       margo.exe: ~bin/gosublime.margo_r17.11.27-1_go?.exe (missing)
|          go.exe: /usr/local/Cellar/go/1.5.2/libexec/bin/go (ok)
|      go.version: go?
|          GOROOT: /usr/local/Cellar/go/1.5.2/libexec/
|          GOPATH: /data/Dev/golang-projects/mahjong/
|           GOBIN: (not set)
|       set.shell: []
|       env.shell: /bin/zsh
|       shell.cmd: ['/bin/zsh', '-l', '-c', '${CMD}']
|    sh.bootstrap: 
|                > 	error running sh-bootstrap.go: package main
|                > 	imports encoding/json
|                > 	imports bytes
|                > 	imports errors
|                > 	imports runtime
|                > 	imports runtime/internal/sys: cannot find package "runtime/internal/sys" in any of:
|                > 	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/internal/sys (from $GOROOT)
|                > 	/data/Dev/golang-projects/mahjong/src/runtime/internal/sys (from $GOPATH)
|                > 
|                > 	go version: `` (raw version string ``)
|                > 	shell bootstrap took 1.443s
|                > 
```

**Comment by DisposaBoy** [comment]
That looks like a problem with your Go installation. Also, Go 1.5 is not supported. The minimum version is Go 1.6 (the current released version of Go is 1.9).
