### ISSUE TITLE
Panic on autocomplete

### ISSUE THREAD

**Issue by mwf** [DisposaBoy/GoSublime#859]
Hi! My gosublime autocompletion eventually stopped working in one of my packages.

I either get an error `[23:36:11] margo: agent#020: ipc: recv: 'int' object has no attribute 'get': 112` or a panic:
```
[23:31:20] margo: agent#014: log: panic: One of the package cache updaters panicked
[23:31:20] margo: agent#014: log: 
[23:31:20] margo: agent#014: log: goroutine 1 [running]:
[23:31:20] margo: agent#014: log: disposa.blue/margo/golang/internal/gocode.update_packages(0xc4201a5148)
[23:31:20] margo: agent#014: log: 	/Users/ikorolev/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/margo/golang/internal/gocode/autocompletecontext.go:463 +0x1a4
[23:31:20] margo: agent#014: log: disposa.blue/margo/golang/internal/gocode.(*auto_complete_context).update_caches(0xc420184440)
[23:31:20] margo: agent#014: log: 	/Users/ikorolev/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/margo/golang/internal/gocode/autocompletecontext.go:178 +0x1a7
[23:31:20] margo: agent#014: log: disposa.blue/margo/golang/internal/gocode.(*auto_complete_context).apropos(0xc420184440, 0xc420244000, 0x1285, 0x1285, 0xc420238370, 0x42, 0x401, 0x2, 0x2, 0x101, ...)
[23:31:20] margo: agent#014: log: 	/Users/ikorolev/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/margo/golang/internal/gocode/autocompletecontext.go:360 +0x1d2
[23:31:20] margo: agent#014: log: disposa.blue/margo/golang/internal/gocode.(*margoState).Complete(0xc4201e40b0, 0x0, 0x0, 0x0, 0xc420186090, 0x21, 0xc42024c4c0, 0x2, 0x2, 0x101, ...)
[23:31:20] margo: agent#014: log: 	/Users/ikorolev/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/margo/golang/internal/gocode/bridge._margo_.go:89 +0x144
[23:31:20] margo: agent#014: log: disposa.blue/margo/golang.(*gocodeCtx).candidates(0xc4201e4160, 0xc420177080, 0xc4201e6900, 0xc4201e4160)
[23:31:20] margo: agent#014: log: 	/Users/ikorolev/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/margo/golang/gocode.go:292 +0x105
[23:31:20] margo: agent#014: log: disposa.blue/margo/golang.(*Gocode).Reduce(0xc420177080, 0xc420172b40, 0x1589840)
[23:31:20] margo: agent#014: log: 	/Users/ikorolev/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/margo/golang/gocode.go:51 +0xa9
[23:31:20] margo: agent#014: log: disposa.blue/margo/mg.ReducerList.ReduceCtx.func1(0x171ada0, 0xc420175230)
[23:31:20] margo: agent#014: log: 	/Users/ikorolev/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/margo/mg/state.go:125 +0x47
[23:31:20] margo: agent#014: log: runtime/pprof.Do(0x171ada0, 0xc420175230, 0xc420177780, 0x1, 0x1, 0xc4201a5910)
[23:31:20] margo: agent#014: log: 	/Users/ikorolev/.gvm/gos/go1.10.3/src/runtime/pprof/runtime.go:35 +0xca
[23:31:20] margo: agent#014: log: disposa.blue/margo/misc/pprof/pprofdo.Do(0x171af20, 0xc420172b40, 0xc420177760, 0x2, 0x2, 0xc4201a5910)
[23:31:20] margo: agent#014: log: 	/Users/ikorolev/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/margo/misc/pprof/pprofdo/pprofdo.go:11 +0x7f
[23:31:20] margo: agent#014: log: disposa.blue/margo/mg.ReducerList.ReduceCtx(0xc4201726e0, 0x5, 0x5, 0xc420172b40, 0xc420172b40)
[23:31:20] margo: agent#014: log: 	/Users/ikorolev/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/margo/mg/state.go:124 +0x12c
[23:31:20] margo: agent#014: log: disposa.blue/margo/mg.storeReducers.Reduce(0xc420178430, 0x1, 0x1, 0xc4201726e0, 0x5, 0x5, 0xc420177060, 0x2, 0x2, 0xc420172af0, ...)
[23:31:20] margo: agent#014: log: 	/Users/ikorolev/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/margo/mg/store.go:22 +0x7c
[23:31:20] margo: agent#014: log: disposa.blue/margo/mg.(*Store).syncRq(0xc42022c000, 0xc42021f340, 0xc4202321b0)
[23:31:20] margo: agent#014: log: 	/Users/ikorolev/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/margo/mg/store.go:98 +0x25f
[23:31:20] margo: agent#014: log: disposa.blue/margo/mg.(*Agent).communicate(0xc42021f340, 0x16b6018, 0xc42021f340)
[23:31:20] margo: agent#014: log: 	/Users/ikorolev/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/margo/mg/agent.go:153 +0xe4
[23:31:20] margo: agent#014: log: disposa.blue/margo/mg.(*Agent).Run(0xc42021f340, 0x0, 0x0)
[23:31:20] margo: agent#014: log: 	/Users/ikorolev/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/margo/mg/agent.go:132 +0x59
[23:31:20] margo: agent#014: log: disposa.blue/margo/cmdpkg/margosublime.Main.func1(0xc42022a000, 0xc42022a000, 0xc4201a5c37)
[23:31:20] margo: agent#014: log: 	/Users/ikorolev/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/margo/cmdpkg/margosublime/main.go:42 +0xb5
[23:31:20] margo: agent#014: log: disposa.blue/margo/vendor/github.com/urfave/cli.HandleAction(0x15a5ce0, 0xc4201783a0, 0xc42022a000, 0xc42016a1e0, 0x0)
[23:31:20] margo: agent#014: log: 	/Users/ikorolev/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/margo/vendor/github.com/urfave/cli/app.go:490 +0xc8
[23:31:20] margo: agent#014: log: disposa.blue/margo/vendor/github.com/urfave/cli.(*App).Run(0xc4201e24e0, 0xc4200ae1e0, 0x3, 0x3, 0x0, 0x0)
[23:31:20] margo: agent#014: log: 	/Users/ikorolev/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/margo/vendor/github.com/urfave/cli/app.go:264 +0x5ee
[23:31:20] margo: agent#014: log: disposa.blue/margo/mgcli.(*App).RunAndExitOnError(0xc4201e24e0)
[23:31:20] margo: agent#014: log: 	/Users/ikorolev/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/margo/mgcli/mgcli.go:12 +0x55
[23:31:20] margo: agent#014: log: disposa.blue/margo/cmdpkg/margosublime.Main()
[23:31:20] margo: agent#014: log: 	/Users/ikorolev/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/margo/cmdpkg/margosublime/main.go:47 +0x268
[23:31:20] margo: agent#014: log: main.main()
[23:31:20] margo: agent#014: log: 	/Users/ikorolev/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/margo/cmd/margo.sublime/main.go:8 +0x20
[23:31:20] margo: agent#014: log: exit status 2
[23:31:20] margo: agent#014: ipc: recv: 'int' object has no attribute 'get': 112
[23:31:20] margo: agent#014: stopping
[23:31:20] margo: agent#015: starting
```

Unfortunately, it's a private code and I can't share it with you.
Do you have any idea what's going on? 
I'd lovely make you a standalone reproduction if I get any clue :)

**Comment by mwf** [comment]
Version info:
```
** 2018-09-10 23:42:08.976660 **:
GoSublime init r18.07.22-1 (0.004s)
|   install margo: no
|   install state: done
| sublime.version: 3176
| sublime.channel: stable
|       about.ann: a18.07.31-1
|   about.version: r18.07.22-1
|         version: r18.07.22-1
|        platform: osx-x64
|            ~bin: ~/Library/Application Support/Sublime Text 3/Packages/User/GoSublime/osx-x64/bin
|       margo.exe: ~bin/gosublime.margo_r18.07.22-1_go1.10.3.exe (ok)
|          go.exe: ~/.gvm/gos/go1.10.3/bin/go (ok)
|      go.version: go1.10.3
|          GOROOT: ~/.gvm/gos/go1.10.3
|          GOPATH: ~/.gvm/pkgsets/go1.10.3/global:~/dev/go
|           GOBIN: (not set)
|       set.shell: []
|       env.shell: /bin/zsh
|       shell.cmd: ['/bin/zsh', '-l', '-c', '${CMD}']
|    sh.bootstrap: 
|                > 	using shell env GOPATH=~/.gvm/pkgsets/go1.10.3/global:~/dev/go
|                > 	using shell env GOROOT=~/.gvm/gos/go1.10.3
|                > 	using shell env PATH=~/.gvm/pkgsets/go1.10.3/global/bin:~/.gvm/gos/go1.10.3/bin:~/.gvm/pkgsets/go1.10.3/global/overlay/bin:~/.gvm/bin:~/.gvm/bin:~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/dev/go/bin
|                > 	go version: `go1.10.3` (raw version string `go1.10.3`)
|                > 	shell bootstrap took 0.485s
|                >
--------------------------------
```

**Comment by DisposaBoy** [comment]
Please migrate to the development branch https://margo.sh/b/migrate/
