### ISSUE TITLE
Blank margo.go file after installation

### ISSUE THREAD

**Issue by errashe** [DisposaBoy/GoSublime#870]
```
reloading settings Packages/User/GoSublime-aux.sublime-settings
[20:02:38] margo: agent#007: log: ``` "C:\\Users\\errashe\\AppData\\Roaming\\Sublime Text 3\\Packages\\GoSublime\\bin\\margo.sublime.exe" -codec msgpack ```
[20:02:38] margo: agent#007: log: store.go:137: started
[20:02:39] margo: agent#007: log: restart.go:146: Mg/Restart: exit status 1
[20:02:39] margo: agent#007: log: ``` go install -v -tags=margo margo.sh/cmd/margo.sublime ```
[20:02:39] margo: agent#007: log: press ` ctrl+. `,` ctrl+x ` to configure margo or check console for errors
[20:02:39] margo: agent#007: log: *Not* using margo extension: Error: cannot find package "margo" in any of:
[20:02:39] margo: agent#007: log: 	C:\Go\src\margo (from $GOROOT)
[20:02:39] margo: agent#007: log: 	C:\Users\errashe\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\margo (from $GOPATH)
[20:02:39] margo: agent#007: log: 	C:\Users\errashe\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\margo
[20:02:39] margo: agent#007: log: agent GOPATH is C:\Users\errashe\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime;C:\Users\errashe\AppData\Roaming\Sublime Text 3\Packages\GoSublime
[20:02:39] margo: agent#007: log: 

** 2018-10-06 20:03:48.927598 **:
mg.extension_file: Cannot create default margo extension package
GoSublime: Traceback (most recent call last):
  File "C:\Users\errashe\AppData\Roaming\Sublime Text 3\Packages\GoSublime\gosubl\margo.py", line 400, in extension_file
    s = open(self.example_extension_file(), 'r').read()
  File "./python3.3/encodings/cp1251.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 787: character maps to <undefined>
--------------------------------
```

And after all installation process my margo.go file empty. Tried to reinstall go, sublime, gosublime and everything in any combinations. Of course working with development branch. Win10 latest update. Any ideas?

**Comment by DisposaBoy** [comment]
Does it work if you edit `C:\Users\errashe\AppData\Roaming\Sublime Text 3\Packages\GoSublime\gosubl\margo.py` and replace line ~400 `s = open(self.example_extension_file(), 'r').read()` with `s = open(self.example_extension_file(), 'rb').read()` i.e. `'r'` with `'rb'` and then press <kbd>ctrl+.</kbd>,<kbd>ctrl+x</kbd>?

**Comment by errashe** [comment]
After deleting margo.go file, and pressing ctrl+.,ctrl+x i've got 
```
** 2018-10-06 20:46:57.851328 **:
mg.extension_file: Cannot create default margo extension package
GoSublime: Traceback (most recent call last):
  File "C:\Users\errashe\AppData\Roaming\Sublime Text 3\Packages\GoSublime\gosubl\margo.py", line 401, in extension_file
    f.write(s)
TypeError: must be str, not bytes
--------------------------------
```

**Comment by DisposaBoy** [comment]
Change the `'x'` on the line above the one you just edited to `'xb'` and try again. That should fix the `TypeError`.

**Comment by errashe** [comment]
Yep, that's fixed everything. Awesome, thanks for fast answer :)

**Comment by DisposaBoy** [comment]
Thanks for the confirmation. I will push an update shortly. You will probably need to undo the changes when you're ready to do a `git pull` to update.
