### ISSUE TITLE
panic: embedded struct field without name?

### ISSUE THREAD

**Issue by runner-mei** [DisposaBoy/GoSublime#886]
````
[16:56:40] margo: agent#007: log: gocode_suggest.go:52: gocode/suggest panic: embedded struct field without name?
[16:56:40] margo: agent#007: log: goroutine 40 [running]:
[16:56:40] margo: agent#007: log: runtime/debug.Stack(0xc00341b4d0, 0xa34d20, 0xc0b0a0)
[16:56:40] margo: agent#007: log: 	d:/tools/go/src/runtime/debug/stack.go:24 +0xae
[16:56:40] margo: agent#007: log: margo.sh/golang.(*gcSuggest).suggestions.func1(0xc0025b4ae0)
[16:56:40] margo: agent#007: log: 	D:/tools/sublime3/Data/Packages/GoSublime/src/margo.sh/golang/gocode_suggest.go:52 +0x67
[16:56:40] margo: agent#007: log: panic(0xa34d20, 0xc0b0a0)
[16:56:40] margo: agent#007: log: 	d:/tools/go/src/runtime/panic.go:513 +0x1c7
[16:56:40] margo: agent#007: log: margo.sh/vendor/kuroku.io/margocode/lookdot.walk(0xc104e0, 0xc00364def0, 0xc002800101, 0xc00341ba80)
[16:56:40] margo: agent#007: log: 	D:/tools/sublime3/Data/Packages/GoSublime/src/margo.sh/vendor/kuroku.io/margocode/lookdot/lookdot.go:77 +0xaf6
[16:56:40] margo: agent#007: log: margo.sh/vendor/kuroku.io/margocode/lookdot.Walk(0xc00341bae0, 0xc00341ba80, 0x2c42)
[16:56:40] margo: agent#007: log: 	D:/tools/sublime3/Data/Packages/GoSublime/src/margo.sh/vendor/kuroku.io/margocode/lookdot/lookdot.go:12 +0xd9
[16:56:40] margo: agent#007: log: margo.sh/vendor/kuroku.io/margocode/suggest.(*Config).Suggest(0xc00341bc78, 0xc0038c3580, 0x3a, 0xc003af2000, 0x6baa, 0x6baa, 0x2c41, 0x9ba3b3, 0xc0000c2860, 0xc0025b4ae0, ...)
[16:56:40] margo: agent#007: log: 	D:/tools/sublime3/Data/Packages/GoSublime/src/margo.sh/vendor/kuroku.io/margocode/suggest/suggest.go:54 +0x5a3
[16:56:40] margo: agent#007: log: margo.sh/golang.(*gcSuggest).suggestions(0xc002aa19f0, 0xc0025b4ae0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
[16:56:40] margo: agent#007: log: 	D:/tools/sublime3/Data/Packages/GoSublime/src/margo.sh/golang/gocode_suggest.go:88 +0x298
[16:56:40] margo: agent#007: log: margo.sh/golang.(*GocodeCalltips).candidate(0xc000057c80, 0xc0025b4ae0, 0xc003af2000, 0x6baa, 0x6baa, 0x2c41, 0xc0004c4960, 0x17, 0x0, 0x0, ...)
[16:56:40] margo: agent#007: log: 	D:/tools/sublime3/Data/Packages/GoSublime/src/margo.sh/golang/gocode_calltips.go:209 +0x140
[16:56:40] margo: agent#007: log: margo.sh/golang.(*GocodeCalltips).process(0xc000057c80, 0xc001ee3c80, 0x0, 0x0)
[16:56:40] margo: agent#007: log: 	D:/tools/sublime3/Data/Packages/GoSublime/src/margo.sh/golang/gocode_calltips.go:127 +0x2d0
[16:56:40] margo: agent#007: log: margo.sh/golang.(*GocodeCalltips).processer(0xc000057c80)
[16:56:40] margo: agent#007: log: 	D:/tools/sublime3/Data/Packages/GoSublime/src/margo.sh/golang/gocode_calltips.go:70 +0x6b
[16:56:40] margo: agent#007: log: created by margo.sh/golang.(*GocodeCalltips).RMount
[16:56:40] margo: agent#007: log: 	D:/tools/sublime3/Data/Packages/GoSublime/src/margo.sh/golang/gocode_calltips.go:42 +0xa2
````

**Comment by runner-mei** [comment]
** 2018-11-18 16:55:07.502324 **:
GoSublime init r18.11.06-1 (0.000s)
|   install margo: no
|   install state: done
| sublime.version: 3176
| sublime.channel: stable
|       about.ann: a18.11.06-1
|   about.version: r18.11.06-1
|         version: r18.11.06-1
|        platform: windows-x64
|            ~bin: D:\tools\sublime3\Data\Packages\User\GoSublime\windows-x64\bin
|       margo.exe: ~bin\gosublime.margo_r18.11.06-1_go1.11.exe (ok)
|          go.exe: d:/tools/go\bin\go.exe (ok)
|      go.version: go1.11
|          GOROOT: d:/tools/go
|          GOPATH: d:/developing/go/3td;d:/developing/go/meijing
|           GOBIN: D:\tools\go\bin
|       set.shell: []
|       env.shell:
|       shell.cmd: ['C:\\WINDOWS\\system32\\cmd.exe', '/C', '${CMD}']
|    sh.bootstrap: 
|                > 	WARNING: GOPATH is different between your shell and ST/GUI environments
|                > 	     shell.GOPATH: d:/developing/go/3td;d:/developing/go/meijing
|                > 	    st/gui.GOPATH: D:\developing\go\meijing\tpt_vendor;D:\developing\go\meijing
|                > 	WARNING: GOROOT is different between your shell and ST/GUI environments
|                > 	     shell.GOROOT: d:/tools/go
|                > 	    st/gui.GOROOT: D:\tools\go
|                > 	using shell env GOBIN=D:\tools\go\bin
|                > 	using shell env GOPATH=d:/developing/go/3td;d:/developing/go/meijing
|                > 	using shell env GOROOT=d:/tools/go
|                > 	using shell env PATH=D:\tools\sublime3\Data\Packages\GoSublime\bin;D:\tools\sublime3\Data\Packages\User\GoSublime\bin;d:/tools/go\bin;d:/developing/go/3td\bin;d:/developing/go/meijing\bin;D:\tools\go\bin;%PATH%;d:/tools/mingw64/bin;~\bin;~\go\bin;C:\Go\bin
|                > 	go version: `go1.11` (raw version string `go1.11`)
|                > 	shell bootstrap took 1.240s
|                >
--------------------------------

[16:55:10] margo: agent#007: ['D:\\tools\\sublime3\\Data\\Packages\\GoSublime\\bin\\margo.sh.exe', 'start', 'margo.sublime', '-codec', 'msgpack']

**Comment by DisposaBoy** [comment]
You can `git pull` to get the fix. I will announce a new release in a few days.
