### ISSUE TITLE
Calltip panics

### ISSUE THREAD

**Issue by alvarolm** [DisposaBoy/GoSublime#941]
I have tried with the current master branch and 19.06.16 using defaults, everything seems to work but call tips always fails here is the error log when trying to query a function inside the bytes packages (also happens with any other packages):

any clues are appreciated, thanks beforehand
```
Gocode pkg: "bytes"
margo: 2019/08/15 23:00:23 broker.go:105: gocode_calltip#mg9.autoken.e2d6e518-32da-4e42-9551-c417066e38b6 PANIC: One of the package cache updaters panicked
goroutine 62 [running]:
gosublime/cmd/margo_pkg.(*Broker).call.func1(0xc0004620a0, 0xc0001662a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:104 +0xbb
panic(0x8b1d40, 0xa09480)
	/opt/dev/globaldep/go/src/runtime/panic.go:522 +0x1b5
gosublime/something-borrowed/gocode.update_packages(0xc0002cf6d0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/autocompletecontext.go:463 +0x18f
gosublime/something-borrowed/gocode.(*auto_complete_context).update_caches(0xc000066500)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/autocompletecontext.go:178 +0x19e
gosublime/something-borrowed/gocode.(*auto_complete_context).apropos(0xc000066500, 0xc0002e8a80, 0x64e5, 0x6a80, 0xc000026150, 0x28, 0x241, 0x1, 0x1, 0xc000026150, ...)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/autocompletecontext.go:360 +0x179
gosublime/something-borrowed/gocode.(*margoState).Complete(0xc00013c0b0, 0x1, 0x0, 0x0, 0xc000022460, 0x15, 0xc000121b30, 0x1, 0x1, 0xc0002e8a80, ...)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/bridge._margo_.go:80 +0x14b
gosublime/cmd/margo_pkg.(*mGocode).completions(0xc000126000, 0xc0002e8a80, 0x64e5, 0x6a80, 0xc000026150, 0x28, 0x241, 0x16, 0x0, 0x0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/m_gocode.go:95 +0x20e
gosublime/cmd/margo_pkg.(*mGocode).calltips(0xc000126000, 0xc0002e8a80, 0x64e5, 0x6a80, 0xc000026150, 0x28, 0x23e, 0x0, 0x0, 0x0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/m_gocode.go:105 +0x1fb
gosublime/cmd/margo_pkg.(*mGocode).Call(0xc000126000, 0x9865b0, 0xc0004620a0, 0xc0001662a0, 0x0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/m_gocode.go:74 +0x13b
gosublime/cmd/margo_pkg.(*Broker).call(0xc0001662a0, 0xc0004620a0, 0xa13e00, 0xc000126000)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:113 +0x9a
gosublime/cmd/margo_pkg.(*Broker).worker(0xc0001662a0, 0xc0000282f0, 0xc0000685a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:188 +0x97
created by gosublime/cmd/margo_pkg.(*Broker).Loop
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:209 +0x11b

goroutine 1 [syscall]:
syscall.Syscall(0x0, 0x0, 0xc000176000, 0x1000, 0x42c27f, 0x8, 0xc000066d00)
	/opt/dev/globaldep/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x0, 0xc000176000, 0x1000, 0x1000, 0x0, 0xc000124220, 0xc0000e4ab0)
	/opt/dev/globaldep/go/src/syscall/zsyscall_linux_amd64.go:732 +0x5a
syscall.Read(...)
	/opt/dev/globaldep/go/src/syscall/syscall_unix.go:172
internal/poll.(*FD).Read(0xc0000aa000, 0xc000176000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/opt/dev/globaldep/go/src/internal/poll/fd_unix.go:165 +0x131
os.(*File).read(...)
	/opt/dev/globaldep/go/src/os/file_unix.go:263
os.(*File).Read(0xc0000a8000, 0xc000176000, 0x1000, 0x1000, 0xc000036500, 0xc000057a30, 0x405765)
	/opt/dev/globaldep/go/src/os/file.go:108 +0x70
bufio.(*Reader).fill(0xc0000684e0)
	/opt/dev/globaldep/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).ReadSlice(0xc0000684e0, 0xc00006850a, 0xc000068000, 0xc000057bf8, 0xc000057ad0, 0x3, 0x0)
	/opt/dev/globaldep/go/src/bufio/bufio.go:356 +0x3d
bufio.(*Reader).ReadBytes(0xc0000684e0, 0xc000057b0a, 0xc000126000, 0x0, 0x0, 0x0, 0x0)
	/opt/dev/globaldep/go/src/bufio/bufio.go:434 +0x70
gosublime/cmd/margo_pkg.(*Broker).accept(0xc0001662a0, 0xc0000685a0, 0xc000166200)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:128 +0x4c
gosublime/cmd/margo_pkg.(*Broker).Loop(0xc0001662a0, 0x980001)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:213 +0x164
gosublime/cmd/margo_pkg.Main()
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/main.go:140 +0x59b
main.main()
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo/main.go:8 +0x20

goroutine 5 [chan receive]:
gosublime/something-borrowed/gocode.new_file_reader.func1(0xc00000e0b0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/utils.go:229 +0x71
created by gosublime/something-borrowed/gocode.new_file_reader
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/utils.go:226 +0x87

goroutine 6 [chan receive, 1 minutes]:
gosublime/cmd/margo_pkg.init.1.func1()
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/g_autoinst.go:114 +0xcb
created by gosublime/cmd/margo_pkg.init.1
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/g_autoinst.go:113 +0x35

goroutine 7 [sleep, 1 minutes, locked to thread]:
runtime.goparkunlock(...)
	/opt/dev/globaldep/go/src/runtime/proc.go:307
time.Sleep(0x77359400)
	/opt/dev/globaldep/go/src/runtime/time.go:105 +0x159
gosublime/cmd/margo_pkg.startOomKiller.func1(0x3e8)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/oom.go:31 +0x9a
created by gosublime/cmd/margo_pkg.startOomKiller
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/oom.go:10 +0x3f

goroutine 8 [sleep, 1 minutes]:
runtime.goparkunlock(...)
	/opt/dev/globaldep/go/src/runtime/proc.go:307
time.Sleep(0x6fc23ac00)
	/opt/dev/globaldep/go/src/runtime/time.go:105 +0x159
gosublime/cmd/margo_pkg.Main.func1(0x6fc23ac00, 0xc0001662a0, 0xc000028280)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/main.go:122 +0xe4
created by gosublime/cmd/margo_pkg.Main
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/main.go:120 +0x6a1

goroutine 9 [chan receive, 1 minutes]:
gosublime/cmd/margo_pkg.Main.func2(0xc0001662a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/main.go:135 +0x11a
created by gosublime/cmd/margo_pkg.Main
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/main.go:134 +0x56b

goroutine 65 [chan send, 1 minutes]:
gosublime/something-borrowed/gocode.update_packages.func1.1(0xc000086420)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/autocompletecontext.go:452 +0x6c
panic(0x8d2be0, 0xc00005c330)
	/opt/dev/globaldep/go/src/runtime/panic.go:522 +0x1b5
gosublime/something-borrowed/gocode.(*gc_bin_parser).parse_export(0xc000468000, 0xc000462020)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/package_bin.go:126 +0x835
gosublime/something-borrowed/gocode.(*package_file_cache).process_package_data(0xc0000b05a0, 0xc0003e0000, 0x6a521, 0x6a7cc)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/package.go:132 +0x4ea
gosublime/something-borrowed/gocode.(*package_file_cache).update_cache(0xc0000b05a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/package.go:92 +0x201
gosublime/something-borrowed/gocode.update_packages.func1(0xc000086420, 0xc0000b05a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/autocompletecontext.go:455 +0x51
created by gosublime/something-borrowed/gocode.update_packages
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/autocompletecontext.go:448 +0xc9

goroutine 11 [chan receive, 1 minutes]:
gosublime/cmd/margo_pkg.(*Broker).worker(0xc0001662a0, 0xc0000282f0, 0xc0000685a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:187 +0xaf
created by gosublime/cmd/margo_pkg.(*Broker).Loop
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:209 +0x11b

goroutine 12 [chan receive, 1 minutes]:
gosublime/cmd/margo_pkg.(*Broker).worker(0xc0001662a0, 0xc0000282f0, 0xc0000685a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:187 +0xaf
created by gosublime/cmd/margo_pkg.(*Broker).Loop
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:209 +0x11b

goroutine 13 [chan receive, 1 minutes]:
gosublime/cmd/margo_pkg.(*Broker).worker(0xc0001662a0, 0xc0000282f0, 0xc0000685a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:187 +0xaf
created by gosublime/cmd/margo_pkg.(*Broker).Loop
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:209 +0x11b

goroutine 14 [chan receive, 1 minutes]:
gosublime/cmd/margo_pkg.(*Broker).worker(0xc0001662a0, 0xc0000282f0, 0xc0000685a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:187 +0xaf
created by gosublime/cmd/margo_pkg.(*Broker).Loop
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:209 +0x11b

goroutine 15 [chan receive, 1 minutes]:
gosublime/cmd/margo_pkg.(*Broker).worker(0xc0001662a0, 0xc0000282f0, 0xc0000685a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:187 +0xaf
created by gosublime/cmd/margo_pkg.(*Broker).Loop
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:209 +0x11b

goroutine 16 [chan receive, 1 minutes]:
gosublime/cmd/margo_pkg.(*Broker).worker(0xc0001662a0, 0xc0000282f0, 0xc0000685a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:187 +0xaf
created by gosublime/cmd/margo_pkg.(*Broker).Loop
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:209 +0x11b

goroutine 49 [chan receive, 1 minutes]:
gosublime/cmd/margo_pkg.(*Broker).worker(0xc0001662a0, 0xc0000282f0, 0xc0000685a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:187 +0xaf
created by gosublime/cmd/margo_pkg.(*Broker).Loop
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:209 +0x11b

goroutine 50 [chan receive, 1 minutes]:
gosublime/cmd/margo_pkg.(*Broker).worker(0xc0001662a0, 0xc0000282f0, 0xc0000685a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:187 +0xaf
created by gosublime/cmd/margo_pkg.(*Broker).Loop
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:209 +0x11b

goroutine 51 [chan receive, 1 minutes]:
gosublime/cmd/margo_pkg.(*Broker).worker(0xc0001662a0, 0xc0000282f0, 0xc0000685a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:187 +0xaf
created by gosublime/cmd/margo_pkg.(*Broker).Loop
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:209 +0x11b

goroutine 52 [chan receive, 1 minutes]:
gosublime/cmd/margo_pkg.(*Broker).worker(0xc0001662a0, 0xc0000282f0, 0xc0000685a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:187 +0xaf
created by gosublime/cmd/margo_pkg.(*Broker).Loop
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:209 +0x11b

goroutine 53 [chan receive, 1 minutes]:
gosublime/cmd/margo_pkg.(*Broker).worker(0xc0001662a0, 0xc0000282f0, 0xc0000685a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:187 +0xaf
created by gosublime/cmd/margo_pkg.(*Broker).Loop
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:209 +0x11b

goroutine 54 [chan receive, 1 minutes]:
gosublime/cmd/margo_pkg.(*Broker).worker(0xc0001662a0, 0xc0000282f0, 0xc0000685a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:187 +0xaf
created by gosublime/cmd/margo_pkg.(*Broker).Loop
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:209 +0x11b

goroutine 55 [chan receive, 1 minutes]:
gosublime/cmd/margo_pkg.(*Broker).worker(0xc0001662a0, 0xc0000282f0, 0xc0000685a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:187 +0xaf
created by gosublime/cmd/margo_pkg.(*Broker).Loop
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:209 +0x11b

goroutine 56 [chan receive, 1 minutes]:
gosublime/cmd/margo_pkg.(*Broker).worker(0xc0001662a0, 0xc0000282f0, 0xc0000685a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:187 +0xaf
created by gosublime/cmd/margo_pkg.(*Broker).Loop
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:209 +0x11b

goroutine 57 [chan receive, 1 minutes]:
gosublime/cmd/margo_pkg.(*Broker).worker(0xc0001662a0, 0xc0000282f0, 0xc0000685a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:187 +0xaf
created by gosublime/cmd/margo_pkg.(*Broker).Loop
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:209 +0x11b

goroutine 58 [chan receive, 1 minutes]:
gosublime/cmd/margo_pkg.(*Broker).worker(0xc0001662a0, 0xc0000282f0, 0xc0000685a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:187 +0xaf
created by gosublime/cmd/margo_pkg.(*Broker).Loop
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:209 +0x11b

goroutine 59 [chan receive, 1 minutes]:
gosublime/cmd/margo_pkg.(*Broker).worker(0xc0001662a0, 0xc0000282f0, 0xc0000685a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:187 +0xaf
created by gosublime/cmd/margo_pkg.(*Broker).Loop
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:209 +0x11b

goroutine 60 [chan receive, 1 minutes]:
gosublime/cmd/margo_pkg.(*Broker).worker(0xc0001662a0, 0xc0000282f0, 0xc0000685a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:187 +0xaf
created by gosublime/cmd/margo_pkg.(*Broker).Loop
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:209 +0x11b

goroutine 61 [chan receive, 1 minutes]:
gosublime/cmd/margo_pkg.(*Broker).worker(0xc0001662a0, 0xc0000282f0, 0xc0000685a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:187 +0xaf
created by gosublime/cmd/margo_pkg.(*Broker).Loop
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/cmd/margo_pkg/broker.go:209 +0x11b

goroutine 70 [chan send]:
gosublime/something-borrowed/gocode.update_packages.func1.1(0xc000086360)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/autocompletecontext.go:452 +0x6c
panic(0x8d2be0, 0xc000322d80)
	/opt/dev/globaldep/go/src/runtime/panic.go:522 +0x1b5
gosublime/something-borrowed/gocode.(*gc_bin_parser).parse_export(0xc0003481c0, 0xc00011fc60)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/package_bin.go:126 +0x835
gosublime/something-borrowed/gocode.(*package_file_cache).process_package_data(0xc0000d25f0, 0xc0002ef500, 0x673b, 0x69e6)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/package.go:132 +0x4ea
gosublime/something-borrowed/gocode.(*package_file_cache).update_cache(0xc0000d25f0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/package.go:92 +0x201
gosublime/something-borrowed/gocode.update_packages.func1(0xc000086360, 0xc0000d25f0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/autocompletecontext.go:455 +0x51
created by gosublime/something-borrowed/gocode.update_packages
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/autocompletecontext.go:448 +0xc9

goroutine 69 [chan send]:
gosublime/something-borrowed/gocode.update_packages.func1.1(0xc000086360)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/autocompletecontext.go:452 +0x6c
panic(0x8d2be0, 0xc000088400)
	/opt/dev/globaldep/go/src/runtime/panic.go:522 +0x1b5
gosublime/something-borrowed/gocode.(*gc_bin_parser).parse_export(0xc0000de2a0, 0xc00030e060)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/package_bin.go:126 +0x835
gosublime/something-borrowed/gocode.(*package_file_cache).process_package_data(0xc0000d25a0, 0xc000350000, 0x37dc3, 0x3806e)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/package.go:132 +0x4ea
gosublime/something-borrowed/gocode.(*package_file_cache).update_cache(0xc0000d25a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/package.go:92 +0x201
gosublime/something-borrowed/gocode.update_packages.func1(0xc000086360, 0xc0000d25a0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/autocompletecontext.go:455 +0x51
created by gosublime/something-borrowed/gocode.update_packages
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/autocompletecontext.go:448 +0xc9

goroutine 71 [chan send]:
gosublime/something-borrowed/gocode.update_packages.func1.1(0xc000086360)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/autocompletecontext.go:452 +0x6c
panic(0x8d2be0, 0xc000312090)
	/opt/dev/globaldep/go/src/runtime/panic.go:522 +0x1b5
gosublime/something-borrowed/gocode.(*gc_bin_parser).parse_export(0xc000348000, 0xc00011fbe0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/package_bin.go:126 +0x835
gosublime/something-borrowed/gocode.(*package_file_cache).process_package_data(0xc0000d2be0, 0xc0003c5300, 0xfd1, 0x127c)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/package.go:132 +0x4ea
gosublime/something-borrowed/gocode.(*package_file_cache).update_cache(0xc0000d2be0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/package.go:92 +0x201
gosublime/something-borrowed/gocode.update_packages.func1(0xc000086360, 0xc0000d2be0)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/autocompletecontext.go:455 +0x51
created by gosublime/something-borrowed/gocode.update_packages
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/autocompletecontext.go:448 +0xc9

goroutine 72 [chan send]:
gosublime/something-borrowed/gocode.update_packages.func1.1(0xc000086360)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/autocompletecontext.go:452 +0x6c
panic(0x8d2be0, 0xc000322d40)
	/opt/dev/globaldep/go/src/runtime/panic.go:522 +0x1b5
gosublime/something-borrowed/gocode.(*gc_bin_parser).parse_export(0xc0003480e0, 0xc00011fc20)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/package_bin.go:126 +0x835
gosublime/something-borrowed/gocode.(*package_file_cache).process_package_data(0xc0000d2c30, 0xc00038a000, 0x220af, 0x2235a)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/package.go:132 +0x4ea
gosublime/something-borrowed/gocode.(*package_file_cache).update_cache(0xc0000d2c30)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/package.go:92 +0x201
gosublime/something-borrowed/gocode.update_packages.func1(0xc000086360, 0xc0000d2c30)
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/autocompletecontext.go:455 +0x51
created by gosublime/something-borrowed/gocode.update_packages
	/home/alvarolm/.config/sublime-text-3/Packages/GoSublime/src/gosublime/something-borrowed/gocode/autocompletecontext.go:448 +0xc9
```

**Comment by DisposaBoy** [comment]
That trace looks like it's all coming from the old version of margo. See https://margo.sh/b/migrate/ for instructions on switching to the `development` branch. You can also follow the same instructions to switch to the `next` branch which has better go.mod support, but might be more unstable.

**Comment by alvarolm** [comment]
thanks, understood, btw I'm using margo version: 18.11.28-1 and just setting "gscomplete_enabled" to true in settings did the trick for me.

thanks for all the work and contribution to the community @DisposaBoy !
