### ISSUE TITLE
Error starting margo

### ISSUE THREAD

**Issue by jdelk** [DisposaBoy/GoSublime#952]
I switched to the development build of GoSublime and reinstalled it. Now I'm getting this error:

```
** 2019-11-29 17:29:55.021246 **:
agent#010: GoSublime: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\GoSublime\gosubl\margo_agent.py", line 176, in _handle_send_ipc
    ipc_enc(rq.data(), self.proc.stdin)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\GoSublime\gosubl\vendor\umsgpack.py", line 527, in _pack3
    _pack_map(obj, fp, options)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\GoSublime\gosubl\vendor\umsgpack.py", line 395, in _pack_map
    pack(v, fp, **options)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\GoSublime\gosubl\vendor\umsgpack.py", line 527, in _pack3
    _pack_map(obj, fp, options)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\GoSublime\gosubl\vendor\umsgpack.py", line 395, in _pack_map
    pack(v, fp, **options)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\GoSublime\gosubl\vendor\umsgpack.py", line 527, in _pack3
    _pack_map(obj, fp, options)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\GoSublime\gosubl\vendor\umsgpack.py", line 395, in _pack_map
    pack(v, fp, **options)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\GoSublime\gosubl\vendor\umsgpack.py", line 521, in _pack3
    _pack_string(obj, fp, options)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\GoSublime\gosubl\vendor\umsgpack.py", line 289, in _pack_string
    fp.write(struct.pack("B", 0xa0 | len(obj)) + obj)
OSError: [Errno 22] Invalid argument
--------------------------------
```

SublimeText version is 3.2.2 (Build 3211) , Go version is 1.13.4 and Python version is 2.7.17

I've tried reinstalling GoSublime several times but I'm still getting the same error.

**Comment by DisposaBoy** [comment]
@jdelk What version of Windows are you using, maybe I Microsoft supplies a VM I can use to reproduce this. Subime Text ships with its own version of Python so I don't think it's related to the one you have installed.
